# Generated by Django 4.0 on 2023-02-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_ref_payment_txid_remove_payment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='typ',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
