# Generated by Django 4.0 on 2023-03-29 13:36

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('cc_number', models.IntegerField(blank=True, null=True)),
                ('cc_cvv', models.IntegerField(blank=True, null=True)),
                ('cc_expiry', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=80, null=True)),
                ('recoveryCode', models.CharField(blank=True, max_length=6, null=True)),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_image_path_profile)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_login', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
