# Generated by Django 4.0 on 2023-02-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_winners_allbet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allbet',
            name='winners',
        ),
        migrations.AlterField(
            model_name='allbet',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='allbet',
            name='number1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allbet',
            name='number2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allbet',
            name='number3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allbet',
            name='number4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allbet',
            name='number5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allbet',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='allbet',
            name='totalpot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='allbet',
            name='winning_one',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='allbet',
            name='winning_two',
            field=models.IntegerField(),
        ),
    ]
