# Generated by Django 4.0 on 2023-02-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0005_userprofile_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
